### ISSUE TITLE
Example data: wrong format?

### ISSUE THREAD

**Issue by ianbstewart** [mitre/tmnt#1]
Hello,

I tried running the example training code and ran into a data error:

```
python bin/train_model.py --tr_vec_file data/train.vec --val_vec_file data/test.vec --vocab_file data/train.vocab --config examples/train_model/model.config --save_dir _experiments/ --log_level info
```

Output:

```
ValueError: Feature indices in SVMlight/LibSVM data file should be sorted and unique.
```

The problem has to do with the format of the `.vec` files that you provided (ex. [train.vec](https://github.com/mitre/tmnt/blob/master/data/train.vec)), because the word indices in the files are not sorted. Once I sorted the indices, the files loaded fine.

**Comment by wellner** [comment]
Thanks for this!  The sample .vec files have been updated to have ascending indices.
